### ISSUE TITLE
currify issue on start

### ISSUE THREAD

**Issue by Craigzyc** [coderaiser/cloudcmd#123]
I'm getting an error when trying to start cloudcmd on node 4.2.6. I have tried finding a solution but don't see any issues that are similar. I appreciate any help

```
/usr/local/lib/node_modules/cloudcmd/node_modules/currify/lib/currify.js:6`
        return fn(...arguments);
                  ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cloudcmd/node_modules/console-io/server/index.js:12:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

7.0.2 **Version** (`cloudcmd -v`): 
4.2.6 **Node Version** `node -v`: 
Linux 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux **OS** (`uname -a` on Linux): 
N/A **Browser name/version**: 
N/A **Used Command Line Parameters**: 
Gritty for console **Changed Config**:

**Comment by coderaiser** [comment]
Fixed with:
- [console-io v5.0.2](https://github.com/cloudcmd/console/releases/tag/v5.0.2)
- [deepword v2.0.2](https://github.com/cloudcmd/deepword/releases/tag/v2.0.2)
- [nomine v1.0.3](https://github.com/coderaiser/node-nomine/releases/tag/v1.0.3)
- [remedy v3.0.1](https://github.com/coderaiser/node-remedy/releases/tag/v3.0.1)
- [salam v1.0.4](https://github.com/coderaiser/node-salam/releases/tag/v1.0.4)
- [omnes v1.0.8](https://github.com/cloudcmd/node-omnes/releases/tag/v1.0.8)

Please run:

```
npm i cloudcmd -g
```

Could you tell me please, why are you using `node v4` and do not upgrade to `v6` or `8`?

**Comment by CraigZych** [comment]
I would love to upgrade. Im deploying to 40+ boxes in the field all on cellular modems of varying speed. I've been trying to avoid having to upgrade them all. All new boxes go out with updated linux and node but i have to still support the older 14.04 linux and node v4 in the field.

Thanks for the fix

**Comment by coderaiser** [comment]
Glad to help :).
