### ISSUE TITLE
Chrome rejects subresources with credentials

### ISSUE THREAD

**Issue by jzaefferer** [coderaiser/cloudcmd#124]
* **Version** (`cloudcmd -v`): Docker image coderaiser/cloudcmd:7.1.0-alpine
* **Node Version** `node -v`: n/a
* **OS** (`uname -a` on Linux): n/a
* **Browser name/version**: Chrome, Version 59.0.3071.115 (Official Build) (64-bit)
* **Used Command Line Parameters**: See below
* **Changed Config**: n/a

Background/usecase: The way we use cloudcmd requires opening a popup with username/password credentials included in the URL, like https://admin:password@host

When using the auth with username and password parameters, and opening the URL is username and password as part of the URL, subresources are incorrectly loaded using those inline credentials, which Chrome now blocks.

To reproduce:
```
docker run -it -p 8765:80 coderaiser/cloudcmd:7.1.0-alpine --port 80 --root /test --auth --username admin --password password
```
Then open http://admin:password@localhost:8765

Chrome logs this:

> [Deprecation] Subresource requests whose URLs contain embedded credentials (e.g. `https://user:pass@host/`) are blocked. See https://www.chromestatus.com/feature/5669008342777856 for more details.

And blocks requests to subresources like this: http://admin:password@localhost:8765/dist/cloudcmd.css

---

I haven't yet looked what's causing this or how to address it. The subresources are loaded using path-absolute URLs, like `src="/cloudcmd.js"`. Not sure why that would cause the actual URL to include the credentials.

May be a trivial issue to fix. Let me know if I can help.

**Comment by coderaiser** [comment]
It is very bad idea to write credentials in url and I understand why developers of `Google Chrome` decided to drop support of it.

Anyways I can not reproduce this on `Chrome Version 62.0.3167.0 (Official Build) canary (64-bit)` while on `Chrome Version 59` file `/cloudcmd.js` is blocked.
It is not a bug of `Cloud Commander` and all resources could not just be inlined in `index.html` by design.

You can use proxy which will get login:password via url field and then will redirect and set auth headers to load `Cloud Commander`s resources properly.

**Comment by jzaefferer** [comment]
Its interesting that this isn't a problem in Canary anymore. This confirms my suspicions that there's actually a bug in the current Chrome, where it correctly rewrites the address to remove the credentials, but then doesn't apply that to subresources.

Since it works in Canary and in non-Chrome browsers, I agree that this isn't a bug in this project. Thanks for your help!
