### ISSUE TITLE
8.5.0 copy/move dialog?

### ISSUE THREAD

**Issue by inamak** [coderaiser/cloudcmd#155]
Hi - am I supposed to see any detailed dialog on copy/move?

I get the little animated blue icon when it is doing the process, but no actual detail.

**Comment by coderaiser** [comment]
What do you mean by detailed dialog? There is `progress` information near blue icon.

**Comment by inamak** [comment]
Hmmm all I see is the icon. No progress information near it. Can you post a screenshot maybe I'm being silly.

**Comment by coderaiser** [comment]
I see there is such a bug. The thing is `progress` should be enabled after one of operations started: `delete`, `copy`, `move`, `pack`, `unpack`. But for `move` and `copy` this didn't work.
 

It should look like this:
![image](https://user-images.githubusercontent.com/1573141/37867874-6eedca04-2fa7-11e8-8aac-cf32d4686e70.png)

Fixed with b287329. Landed in [v8.5.1](https://github.com/coderaiser/cloudcmd/releases/v8.5.1).

Thank you :).

**Comment by inamak** [comment]
Hi - I am on 8.5.2 now and still only see the icon on copy - no percentage? Cleared browser cache but did not help.
