### ISSUE TITLE
Progress icon disappearing

### ISSUE THREAD

**Issue by csazku** [coderaiser/cloudcmd#187]
* **Version**: v10.5.3 
* **Node Version**: v10.4.0
* **OS**: Ubuntu 16
* **Browser name/version**: Chrome v69.0.3497.81
* **Used Command Line Parameters**: 
* **Changed Config**: 

When copying, deleting or unpacking files the progress icon disappears after changing directories in any of the panels. It works fine when uploading files.

**Comment by coderaiser** [comment]
Thank you, it is known behavior, it occurs because [progress icon](https://github.com/coderaiser/cloudcmd/blob/v10.5.3/client/dom/images.js#L77) appended to [a template](https://github.com/coderaiser/cloudcmd/blob/v10.5.3/tmpl/fs/path.hbs) which is re-rendered on every directory change. I do not know how to fix it now, would be grateful for any ideas :).

**Comment by csazku** [comment]
I'm not really knowledgeable in node so unfortunately I can't help you out, but I hope someone who can sees this. :)

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.
