### ISSUE TITLE
Extraction of .rar files

### ISSUE THREAD

**Issue by vibratim** [coderaiser/cloudcmd#189]
Hello,
is there a possibility to use cloudcmd to extract .rar files?

**Comment by coderaiser** [comment]
No there is no such possibility because there is no js implementation of packing and unpacking of `rar`-archives in `nodej.js` with the help of `streams` whithout `native` modules or `rar` installed.

There is a library [rar-stream](https://www.npmjs.com/package/rar-stream) but it **does not support decompression** and requires `node >= 8.0.0`.

If you will find any library that solves compression and decompression of `rar` files put it here and I'll think how to add support of it to [inly](https://github.com/coderaiser/node-inly) and `Cloud Commander` :).

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity.

**Comment by coderaiser** [comment]
@vibratim you can cheer [rar-stream](https://github.com/1313/rar-stream) author on so he proceed his work, and ask about decompression support, to make possible adding support of `rar` to Cloud Commander 🙂

**Comment by werty1st** [comment]
How about this one? https://www.npmjs.com/package/node-unrar-js

**Comment by coderaiser** [comment]
Is it supports streams?

**Comment by werty1st** [comment]
I'm not sure. But it doesn't seem to support multipart archives. to bad.

**Comment by werty1st** [comment]
I found node-unar which I was able to use to decompress a small (5x250Kb) multipart archive. But unfortunately it didn't decompress my large 5GB multipart archive.
https://github.com/coderaiser/node-inly/compare/master...werty1st:node-inly:master


During my tests I recognized that the decompression dialog may not be put in a background mode. But my intention was like queuing multiple decompression jobs. That way I would not have to come back an check if it finished and start the next one.

**Comment by coderaiser** [comment]
You can also use `unrar` binary utility in terminal with help of [User Menu](https://cloudcmd.io/#user-menu).

**Comment by werty1st** [comment]
Thank you. Could it run multiple times/simultaneous in background?

**Comment by coderaiser** [comment]
It can run anything you can run using Terminal
