### ISSUE TITLE
 error in /usr/lib/node_modules/cloudcmd/server/config.js:55 ...rootConfig error

### ISSUE THREAD

**Issue by mattman73** [coderaiser/cloudcmd#201]
* **Version** (`cloudcmd -v`):  11.5.3
* **Node Version** `node -v`:   6.12.0
* **OS** (`uname -a` on Linux):  Linux host.localhost 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* **Browser name/version**:  unable to get this far
* **Used Command Line Parameters**:  unable to get this far
* **Changed Config**:  no change standard install version

Run cloudcmd
got this error.
/usr/lib/node_modules/cloudcmd/server/config.js:55
    ...rootConfig,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/bin/cloudcmd.js:12:16)

Any pointers on what might be wrong would be great thanks,

**Comment by coderaiser** [comment]
The thing is `node version < 8` is not supported since [Cloud Commander v11.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v11.0.0) major release.

Please upgrade to `v10`, which [became LTS this month](https://github.com/nodejs/Release#release-schedule), or at least to `v8`, `v6` will be deprecated in April.

Is it works for you?

**Comment by coderaiser** [comment]
The thing is `node version < 8` is not supported since [Cloud Commander v11.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v11.0.0) major release.

Please upgrade to `v10`, which [became LTS this month](https://github.com/nodejs/Release#release-schedule), or at least to `v8`, `v6` will be deprecated in April.

Is it works for you?

**Comment by mattman73** [comment]
I have update node to v10.12.0 and all is working now, many thanks
