### ISSUE TITLE
Multiple instances with different configurations as middleware

### ISSUE THREAD

**Issue by jcaron23** [coderaiser/cloudcmd#208]
* **Version** (`cloudcmd -v`): 11.8.3
* **Node Version** `node -v`: 8.11.1
* **OS** (`uname -a` on Linux): macOS 10.13.6
* **Browser name/version**: Safari 12.0.1
* **Used Command Line Parameters**: n/a
* **Changed Config**: 

First of all, thanks for the great work!

Is there a way to use different configs for multiple instances of cloudcmd used as middleware?

The idea is to have different URL prefixes that would give different accesses (for instance one has a root restricting access to only specific files, while another one has a different root giving access to other files).

A quick test seems to indicate that cloudcmd uses the config given when first instantiated, and ignores further configurations.

Is this something possible at all? Or is there maybe a way to change the config on the fly with another middleware?

I have tried playing with calling cloudcmd/server/config to change settings on the fly, but I'm not sure this is really fully supported.

Thanks!

**Comment by coderaiser** [comment]
For globally installed instanced of `Cloud Commander` there is such and option as [--config](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/bin/cloudcmd.js#L259):

```
cloudcmd --config ./config.json
```  

But it is only read `config` at start up, and if you change something with help of `Config Dialog` it will be saved to `~/.cloudcmd.json` no matter what are you use to change config:
- `middleware`
- `separate process`
- [distribute](http://cloudcmd.io/#distribute)

In globally installed version [default config](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/json/config.json] read first, then `~/.cloudcmd.json` all this happening in [server/config.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/config.js#L37-L57), and this all done before reading config with help of `--config` option.

There is an interesting idea to provide `config path` option to middleware, to have ability to use different files for configuration options for different mount points.

> A quick test seems to indicate that cloudcmd uses the config given when first instantiated, and ignores further configurations.

Have you used `Config Dialog` to change config? What options do you need to change? Options not listed in `Config Dialog` can't be configured on a runtime (because it is initialization options, but it relates to global install), like this one:
- `port`
- `ip`
- `prefix`
- `import`
- `export`
- etc...

But you can change next options:
- `username`
- `password`
- `auth`
- `editor`
- etc...

> The idea is to have different URL prefixes that would give different accesses (for instance one has a root restricting access to only specific files, while another one has a different root giving access to other files).

`root` can be changed, but when you change it in one middleware it will be saved in `~/.cloudcmd.json` and changed in [server/config.js](https://github.com/coderaiser/cloudcmd/blob/v11.8.3/server/config.js#L54-L57) variable which will be used in both places. 

To have ability to use different configs for every mount point inside one process `config manager` should be improved, do you have any ideas how it could be done? How do you want to change config options in a public api?

This is a very good idea for a pull request 🙂.

**Comment by coderaiser** [comment]
Added support of `Config Manager` in [Cloud Commander v12.6.0](https://github.com/coderaiser/cloudcmd/releases/tag/v12.6.0) 🎉.

@jcaron23  Is it works for you?
