### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by Kruk79** [coderaiser/cloudcmd#303]
* **Version** (`cloudcmd -v`):  latest
* **Node Version** `node -v`: 
* **OS** (`uname -a` on Linux): RPI 3 with OMV 5
* **Browser name/version**: Chrome
* **Used Command Line Parameters**: none
* **Changed Config**: none

Once I press Deploy in stacks/portainer I'm having this error:

![Capture](https://user-images.githubusercontent.com/52547497/98992594-482f2900-2525-11eb-92bc-d4f9fb362fe0.PNG)

Any suggestion?

Thanks

**Comment by coderaiser** [comment]
@Kruk79 What `Cloud Commander` image do you use?
@timoknapp could you please help?

**Comment by Kruk79** [comment]
I did pulled the image in portianer using coderaiser/cloudcmd. It was successful but there was no image on the list. So i just went to stacks and tried to add new stack using the code from your docker website.

**Comment by timoknapp** [comment]
Hi @Kruk79 ,
Since you are running on an `arm`-based architecture like a RPI, you need to also use an `arm`-based image. Could you please try [this](https://hub.docker.com/r/team0/rpi-cloudcmd) image instead and let me know if this works for you. The current image of `cloudcmd` still has some issues when running on an `arm` architecture.

Regards
Timo

**Comment by Kruk79** [comment]
Thank you. This worked perfectly.

Many thanks
