### ISSUE TITLE
feat: double click on zip shows file list instead of the binary file

### ISSUE THREAD

**Issue by stuckless** [coderaiser/cloudcmd#309]
It would be cool if when you double-click on a zip, to view it, it would show the file list of the zip file rather than the binary blob.  This is similar to how in Linux if you do something like `less file.zip` it will just show the file list and not the binary blob.

BTW, this is a very nice tool.  I only recently found this and I am loving it.  Thank you!

**Comment by coderaiser** [comment]
Glad to here that :). I think such feature makes sense, and this is a very good idea for a Pull Request.

**Comment by stuckless** [comment]
I did take a quick look at the code to see how this might be done... but I couldn't really see how the view.js would get that information.  It looks like you get a URL to the file, that returns the contents, so, I'm thinking this may require either some parameters that are passed on the URL, etc.  So, then I decided to add a feature request ;)  If you offer some direction, I can probably open a PR.

**Comment by coderaiser** [comment]
Right now [inly](https://github.com/coderaiser/node-inly) used for files unpacking, and `inly` uses [onezip](https://github.com/coderaiser/node-onezip) for zip unpacking, so it should be simplified version, which only get list of files, instead of unpacking, and would be better to support other archive types as well (which is supported by inly). This module can be used in [server/rest](https://github.com/coderaiser/cloudcmd/blob/v14.9.3/server/rest/index.js) then. I’ll think how it can be solved. Could you please tell me what exactly do you expect to see? Is it just a View with list of files, or a tree? Or you want to navigate through directory structure of an archive?

**Comment by stuckless** [comment]
I think it would be fine to see a list of files.  I don't think it needs to be interactive.  This is what you see when you do `less file.zip`
![image](https://user-images.githubusercontent.com/1056553/103169879-b72ebb80-480d-11eb-8b9a-0a7292f0f38b.png)

I get that many file managers will do something much fancier, and extract the contents to a temp area and create a virtual filesystem that you can then interact with, view files in the zip, etc, but that's more than what I was asking :)

**Comment by coderaiser** [comment]
I agree this is a very useful feature, and I would like `Cloud Commander` have such ability :). So we can start from adding support of `zip` files in [restafary](https://github.com/coderaiser/node-restafary/blob/master/server/restafary.js#L199-L208) in separate file `archive.js` with to methods:
- `isArchive(filename)` - check is file we need is an acrhive
- `listArchive(filename)` - will read stream and get the list of files

Here is an example of how it can be implemented from [node-ls-archive](https://github.com/atom/node-ls-archive/blob/master/src/ls-archive.coffee#L65-L84) (maybe you will find some other module, the downside of this one is requiring modules inside functions). Anyways we can event start from using this module.

Most work with `zip` files is handled by [yauzl](https://github.com/thejoshwolfe/yauzl).

So this is the simplest and fastest way of implementing such feature, I'm not sure if `restafary` is correct place to do such operations, but this functions can be moved in future, so that's OK for now :).

**Comment by stuckless** [comment]
FYI... I created a PR for restafary... not sure if this is what you intended, and, I'm unable to create a unit test for it.

https://github.com/coderaiser/node-restafary/pull/1

**Comment by coderaiser** [comment]
[Just landed](https://github.com/coderaiser/cloudcmd/releases/tag/v15.1.0) support of working with files in `zip` archives like with regular files :) 🎉  
It is read only for now. Is it works for you?

**Comment by stuckless** [comment]
It's even better than what I asked for :)  It's great that you can navigate inside the zip file, and then view text files, etc.

Thank you again for a great piece of software.

**Comment by coderaiser** [comment]
Just landed [ability to edit files inside zip archives](https://github.com/coderaiser/cloudcmd/releases/tag/v15.5.0) 🎈

**Comment by coderaiser** [comment]
Just landed ability to [copy and move files from/to archives](https://github.com/coderaiser/cloudcmd/releases/tag/v15.7.0) 🎈
