### ISSUE TITLE
Security risk

### ISSUE THREAD

**Issue by OnBartt** [coderaiser/cloudcmd#329]
Hi :),

First of all, I want to really thank you for this project. It is the most simple soft for its purpose which I found, and it works lika a charm. So thank you very much.

The feature which I miss the most, is the user and permission system, but I saw there is different thread for this.

Anyway, the thing what bothers me is the fact, that when you run the cloudcmd with some credentials and auth on, then go to the website and open the source code of the page with the login/passowrd box, you can see target hash and login name in the html code (CloudCmd function parameters), which I think it is an unnecessary exposure of the sensitive information. Well, I know, it is just a hash :). But there is also a name of used algorithm, which I do not like as well. Anyway, I know you still need to use a huge brute force to break it down, but I think the more obstacles in the attacker's way, the better for the security :).
I would try to implement this by myself and aks you for pull afterwards, but I am not PHP nor JS coder :(. 

Thanks a million for any feedback 

OnBartt

**Comment by coderaiser** [comment]
Hi @OnBartt, thank you :), I glad that `Cloud Commander` is useful.

I don’t think that storing hash of a password in `index.html` with the rest config fields can be security risk, because it long enough and easily can be changed with help of any supported by OpenSSL algo, and protected with basic authorization, when auth is enabled. Anyways the place where config placed into `index.html` located in: https://github.com/coderaiser/cloudcmd/blob/a6a1e80afb994a83fdda8d1777580c953e4f4414/server/route.js#L166

And `username` with `password` hash can be cut from it.

**Comment by coderaiser** [comment]
Next modules on the client side, needs `username` and `hash of a password` to initiate `web socket connection`:
- `client/modules/config/index.js`
- `client/modules/edit-file.js`
- `client/modules/konsole.js`
- `client/modules/operation/index.js`
- `client/modules/terminal-run.js`
- `client/modules/terminal.js`

It is initiated using `JavaScript` so in some place accessible by `JavaScript` hash of a a password should be kept (It can't be cookies, and there is no big difference between storing hash in `markup` or in `localStorage` or `indexedDB`). Otherwise to access any of this resources password should be asked and user should type it again and again.

So I close it for now, if you have any ideas how to make things better and simpler from user, developer and security perspective, feel free to share :).
