### ISSUE TITLE
-p password argument ignored when starting cloudcmd

### ISSUE THREAD

**Issue by jojow** [coderaiser/cloudcmd#64]
Hi,

I tried cloudcmd through Docker, using the following command:

`docker run -d -p 8000:8000 coderaiser/cloudcmd:5.2.3 npm start -- --root /data -u admin -p sOmEpAsSwOrD`

However, the -p password parameter seems to be ignored. cloudcmd runs perfectly, but I can access it *without* giving any password. So, everyone can access.

Is this a bug or did I miss anything?

Thanks!

Johannes

**Comment by jojow** [comment]
Btw, the `--root /data` argument works perfectly, meaning I can only access files in this (mounted) directory.

**Comment by coderaiser** [comment]
Hi @jojow,
This is because you did not set flag `auth`, it is `false` by default. So you just set `username` and `password` but did not turn on authorisation. With all parameters command will look like:

`docker run -d -p 8000:8000 coderaiser/cloudcmd:5.2.3 npm start -- --root /data --auth -u admin -p sOmEpAsSwOrD`

And starting from next version you could use just:
`docker run -d -p 8000:8000 coderaiser/cloudcmd:5.2.3 --root /data --auth -u admin -p sOmEpAsSwOrD`

You could also try [alpine](http://www.alpinelinux.org/) build (based on [alpine-node](https://hub.docker.com/r/mhart/alpine-node/), which is much smaller then official docker image of node) with:
`docker run -d -p 8000:8000 coderaiser/cloudcmd:5.2.3-alpine --root /data --auth -u admin -p sOmEpAsSwOrD`

**Comment by jojow** [comment]
Great, thanks a lot! Now it works! :-)

**Comment by dtk78** [comment]
Hi 
do you know how I can set up with auth in a file docker-compose.yml ?
Regards

**Comment by coderaiser** [comment]
@dtk78 you can use `environment variables`:
- `CLOUDCMD_AUTH`
- `CLOUDCMD_USERNAME`
- `CLOUDCMD_PASSWORD`

in [docker-compose file](https://docs.docker.com/compose/environment-variables/#substituting-environment-variables-in-compose-files) or in [env file](https://docs.docker.com/compose/env-file/).

**Comment by dtk78** [comment]
Hello,

Thanks a lot for you reply.
how can I also setup this argument  --root /project in my docker-compose.yml file ?
and --one-panel-mode ?
Regards

**Comment by dtk78** [comment]
hello,

Is it possible to setup default user for creating a file or directory ?
I can see that the default owner is root for creating a new directory or file

Regards

**Comment by coderaiser** [comment]
> how can I also setup this argument --root /project in my docker-compose.yml file ?
and --one-panel-mode ?

I have no idea :). There is no way to set `--root` and `one panel mode` via env variables In Cloud Commander but it is a great idea for a [pull request](https://github.com/coderaiser/cloudcmd/pull/126/files) :).

>Is it possible to setup default user for creating a file or directory ?
I can see that the default owner is root for creating a new directory or file

You should build your own docker image and create user.

**Comment by dtk78** [comment]
Hi,

Do you know how I can make chown after creating a file or after copying some files ?
or is there any pluggins to get an option chown with a right clic ?

Do I need to add a function chmod in a .js file ?

Thanks for your help
Regards

**Comment by coderaiser** [comment]
You can use `console` or `terminal` for this purpose.

**Comment by coderaiser** [comment]
In [v7.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v7.3.0) landed support of environment variables `CLOUDCMD_ROOT` and `CLOUDCMD_ONE_PANEL_MODE`.
