### ISSUE TITLE
Changing linux user to gain access to files with different linux owners

### ISSUE THREAD

**Issue by gbrault** [coderaiser/cloudcmd#84]
This is more of a question!

First thanks a lot for this wonderful server!

When I am not the linux owner of a file, I can't do anything with it (access denied): view, edit, download
Would it be possible to change the personae to gain access to those files?

a kind of su - <new user>?

What do you think?

(`cloudcmd -v`): v5.7.4
`node -v`: 6.9.1
(`uname -a` on Linux): Linux cerasolar 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
: Chrome Version 54.0.2840.71 m (64-bit) on a remote machine

BR

**Comment by coderaiser** [comment]
You can do this with help of a `Console`, actually. You can run it with `~` key and do things you want. There is no other way to do it right now.

**Comment by gbrault** [comment]
Thanks for the advice. Could you please elaborate a bit to make sure I understand correctly?  Thanks!

**Comment by coderaiser** [comment]
There is one problem with this: unfortunately you can't send username and password to `su` command in current implementation of [console](https://github.com/cloudcmd/console). One of the ways is using [sticky bit](https://en.wikipedia.org/wiki/Sticky_bit), also you can add users to [suders](http://serverfault.com/questions/17814/how-can-i-allow-one-user-to-su-to-another-without-allowing-root-access/17818#17818), but again if you need to send password, nothing will workout.

If you know what you are doing you can run `Cloud Commander` as root, and then use `sudo` in `Console` without typing password, it is not recommended (because of security reasons), but possible. You should set long strong password in `Cloud Commander` in this case.

**Comment by gbrault** [comment]
I use cloudcmd with nodered, I can start cloudcmd on-demand and starting it as sudo cloudcmd <options> works. Using iframe in nodered template I can use cloudcmd with node-red dashboard. When I  don't need cloudcmd, I stop it to avoid security holes with having it open to long even with password protection. To have all that protected, I use nginx with https as a reverse proxy (easy to setup).
With this, I can of course even set the "root" directory while starting cloudcmd depending on what I am doing on the site.
I tried it and so far this works great! Thanks again

**Comment by coderaiser** [comment]
Glad to help :).

**Comment by coderaiser** [comment]
Can be solved with help of a [terminal](https://github.com/coderaiser/cloudcmd/releases/tag/v6.7.0).
